#h5
question = input("Ask about UI/UX Course:")

question = input("hi")

print("Hey,How Are You,How Can I Help You?")
question = input("What is UI/UX design and why is it important?")
print("UI/UX design focuses on creating interfaces that are intuitive, easy to use, and visually appealing. It’s important because it improves how users interact with a product, increasing satisfaction and engagement. ")

question = input("What is the difference between UI and UX design?")
print("UI (User Interface) deals with the look and feel — layout, colors, typography, and visual elements.UX (User Experience) focuses on overall user satisfaction, usability, and how easy it is to accomplish tasks.")
question = input("What tools do UI/UX designers commonly use?")
print("Common tools include Figma, Adobe XD, Sketch, InVision, and Axure RP for creating wireframes, prototypes, and designs.")
question = input("What is a wireframe?")
print("A wireframe is a simplified layout that shows the structure and placement of interface elements without visual styling — used to plan and organize before final design.")
question = input("What is a prototype and why is it important?")
print("A prototype is a working model of a design that simulates functionality. It’s important for testing ideas, gathering user feedback, and improving the design before launch.")
question = input("How do you conduct usability testing?")
print("Define test goals, recruit users, give them tasks to complete using the design, observe their interactions, and collect feedback to identify usability issues.")
question = input("What makes a design user-friendly?")
print("Clarity, consistency, intuitive navigation, fast performance, and accessibility for all users are key to making a design user-friendly.")
question = input("How do you ensure accessibility in UI/UX design?")
print("Follow accessibility standards like WCAG — use sufficient color contrast, support keyboard navigation, add alt text for images, and use semantic markup so people with disabilities can use the design.")
question = input("What are micro-interactions?")
print("Small interactions that give feedback and enhance usability — e.g., a button changing color on click or showing a loader while processing an action.")
question = input("How do you handle feedback in your design work?")
print("Collect feedback from users/stakeholders, prioritize necessary changes based on usability impact, and refine the design accordingly.")
question = input("Explain low-fidelity vs high-fidelity prototypes.")
print("Low-fidelity: Simple sketches/wireframes that focus on layout and structure.High-fidelity: Detailed, interactive designs with real visuals and interactions.")
question = input("What is responsive design and why is it important?")
print("It ensures layouts adapt to different screen sizes (mobile, tablet, desktop), giving users a consistent and optimized experience on any device.")
question = input("How would you prioritize features when designing a product?")
print("Prioritize features based on user needs and business goals, then consider technical feasibility and impact.")
question = input("Why is user empathy important in UX design?")
print("Empathy helps designers understand users’ needs, motivations, and frustrations, leading to solutions that truly solve real user problems.")
question = input("What is the role of motion design in UI/UX?") 
print("Used to guide user attention, provide feedback, and make interactions feel natural — but should be subtle and purposeful.")
    